In [ ]:
np.random.seed(5)
val = np.random.randint(0,100,size=(9,9))
print(val)

[[99 78 61 16 73  8 62 27 30]
 [80  7 76 15 53 80 27 44 77]
 [75 65 47 30 84 86 18  9 41]
 [62  1 82 16 78  5 58  0 80]
 [ 4 36 51 27 31  2 68 38 83]
 [19 18  7 30 62 11 67 65 55]
 [ 3 91 78 27 29 33 89 85  7]
 [16 94 14 90 31  9 38 47 16]
 [ 5 34 45 59 24 13 31 32 76]]


In [ ]:
B = []
for i in range (0,val.shape[0],1):
  temp = val[i,:].mean()
  B.append(temp)
print(B)

[50.44444444444444, 51.0, 50.55555555555556, 42.44444444444444, 37.77777777777778, 37.111111111111114, 49.111111111111114, 39.44444444444444, 35.44444444444444]


In [ ]:
C =np.zeros(A.shape[0],A.shape[1]))
ZerosCount = 0
Non_Zero_Count = 0
for i in range(val.shape[0]):
    for j in range(val.shape[1])):
        if(val[i,j]>B[i]:
            C[i,j] = 0
            ZerosCount = ZerosCount+1
        else:
            C[i,j] = A[i,j]
            Non_zero

In [ ]:
import pandas as pd
path = './ign.csv'
data = pd.read_csv(path)
print(type(data))
print(data.shape)

<class 'pandas.core.frame.DataFrame'>
(18625, 10)


In [ ]:
data.iloc[2:6,[3,0,4]]

platform score_phrase  score
2           iPad        Great    8.5
3       Xbox 360        Great    8.5
4  PlayStation 3        Great    8.5
5      Macintosh         Good    7.0

In [ ]:
data.head()

score_phrase                                              title  \
0      Amazing                            LittleBigPlanet PS Vita   
1      Amazing  LittleBigPlanet PS Vita -- Marvel Super Hero E...   
2        Great                               Splice: Tree of Life   
3        Great                                             NHL 13   
4        Great                                             NHL 13   

                                                 url          platform  score  \
0             /games/littlebigplanet-vita/vita-98907  PlayStation Vita    9.0   
1  /games/littlebigplanet-ps-vita-marvel-super-he...  PlayStation Vita    9.0   
2                          /games/splice/ipad-141070              iPad    8.5   
3                      /games/nhl-13/xbox-360-128182          Xbox 360    8.5   
4                           /games/nhl-13/ps3-128181     PlayStation 3    8.5   

        genre editors_choice  release_year  release_month  release_day  
0  Platformer              Y          2012              9           12  
1  Platformer              Y          2012              9           12  
2      Puzzle              N          2012              9           12  
3      Sports              N          2012              9           11  
4      Sports              N          2012              9           11

In [ ]:
data.tail()


score_phrase                                    title  \
18620         Good                Tokyo Mirage Sessions #FE   
18621      Amazing        LEGO Star Wars: The Force Awakens   
18622     Mediocre  Star Ocean: Integrity and Faithlessness   
18623  Masterpiece                                   Inside   
18624  Masterpiece                                   Inside   

                                                     url       platform  \
18620  /games/fire-emblem-x-shin-megami-tensei/wii-u-...          Wii U   
18621  /games/lego-star-wars-the-force-awakens/ps4-20...  PlayStation 4   
18622                   /games/star-ocean-5/ps4-20035681  PlayStation 4   
18623             /games/inside-playdead/xbox-one-121435       Xbox One   
18624                 /games/inside-playdead/pc-20055740             PC   

       score              genre editors_choice  release_year  release_month  \
18620    7.6                RPG              N          2016              6   
18621    9.0  Action, Adventure              Y          2016              6   
18622    5.8                RPG              N          2016              6   
18623   10.0          Adventure              Y          2016              6   
18624   10.0          Adventure              Y          2016              6   

       release_day  
18620           29  
18621           29  
18622           28  
18623           28  
18624           28

In [ ]:
data.loc[2:5,['score_phrase','score']]

score_phrase  score
2        Great    8.5
3        Great    8.5
4        Great    8.5
5         Good    7.0

In [ ]:
#all samples accessing using column labels
data[['score','platform']]

score          platform
0        9.0  PlayStation Vita
1        9.0  PlayStation Vita
2        8.5              iPad
3        8.5          Xbox 360
4        8.5     PlayStation 3
...      ...               ...
18620    7.6             Wii U
18621    9.0     PlayStation 4
18622    5.8     PlayStation 4
18623   10.0          Xbox One
18624   10.0                PC

[18625 rows x 2 columns]

In [ ]:
data.info

<bound method DataFrame.info of       score_phrase                                              title  \
0          Amazing                            LittleBigPlanet PS Vita   
1          Amazing  LittleBigPlanet PS Vita -- Marvel Super Hero E...   
2            Great                               Splice: Tree of Life   
3            Great                                             NHL 13   
4            Great                                             NHL 13   
...            ...                                                ...   
18620         Good                          Tokyo Mirage Sessions #FE   
18621      Amazing                  LEGO Star Wars: The Force Awakens   
18622     Mediocre            Star Ocean: Integrity and Faithlessness   
18623  Masterpiece                                             Inside   
18624  Masterpiece                                             Inside   

                                                     url          platform  \
0            

In [ ]:
#access the scores of all the games
score = data['score']
#average of the score
avg = score.mean()
mn = score.min()
mx = score.max()
var = score.var()
std = score.std()

print("variance: " , var)
print("Average: " , avg)
print("Minimum: " ,mn)
print("Maximum: " , mx)
print("Standard Deviation: " , std)

variance:  2.930039657164422
Average:  6.950459060402685
Minimum:  0.5
Maximum:  10.0
Standard Deviation:  1.7117358608045874


In [ ]:
score.describe()

count    18625.000000
mean         6.950459
std          1.711736
min          0.500000
25%          6.000000
50%          7.300000
75%          8.200000
max         10.000000
Name: score, dtype: float64

In [ ]:
for i in range(0,10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
#how many unique score phrases
phrase = data['score_phrase'].unique()
print(phrase)

['Amazing' 'Great' 'Good' 'Awful' 'Okay' 'Mediocre' 'Bad' 'Painful'
 'Unbearable' 'Disaster' 'Masterpiece']


In [ ]:
#how many years of data you have
year = data['release_year'].unique()
print("all year information:")
print(year)

all year information:
[2012 2013 1996 1970 1997 1998 1999 2000 2001 2002 2003 2004 2005 2006
 2007 2008 2009 2010 2011 2014 2015 2016]


In [ ]:
#how many games are there in each year
games_number = data['release_year'].value_counts()
print(games_number)

release_year
2008    1915
2009    1687
2007    1610
2010    1363
2006    1208
2005    1088
2011    1073
2000    1045
2004     997
2003     969
2002     936
1999     775
2012     753
2013     696
2001     688
2014     537
2015     365
1998     339
2016     226
1997     205
1996     149
1970       1
Name: count, dtype: int64


In [ ]:
score_phrase = data['score_phrase'].value_counts()
print(score_phrase)

score_phrase
Great          4773
Good           4741
Okay           2945
Mediocre       1959
Amazing        1804
Bad            1269
Awful           664
Painful         340
Unbearable       72
Masterpiece      55
Disaster          3
Name: count, dtype: int64
